import{a as b,S as L,i as w}from"./assets/vendor-CNqCr-V-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&u(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const p=(t,s)=>b.get("https://pixabay.com/api/",{params:{key:"53333096-0ed2bac8b305690550bcf3f17",image_type:"photo",orientation:"horizontal",safesearch:!0,q:`${t}`,per_page:15,page:s}}).then(l=>l.data),$=t=>{const{webformatURL:s,largeImageURL:l,tags:u,likes:e,views:r,comments:n,downloads:E}=t;return`<li class="gallery-item">
          <a class="img-link" href="${l}"><img class="img" src="${s}" alt="${u.split(",").slice(0,3).join(",")}"/></a>
          <ul class="img-stats-list">
            <li class="img-stats-item"><h3 class="img-stats-title">likes</h3><p class="img-stats">${e}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">views</h3><p class="img-stats">${r}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">comments</h3><p class="img-stats">${n}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">downloads</h3><p class="img-stats">${E}</p></li>
          </ul>
        </li>`},q=new L(".img-link",{captionsData:"alt",captionDelay:250}),c=t=>w.show({message:`${t}`,color:"red",position:"topRight",close:!1}),g=t=>{const s=t.map(l=>$(l)).join("");i.listEl.insertAdjacentHTML("beforeend",s),q.refresh()},R=()=>{i.listEl.innerHTML=""},y=()=>{i.loaderEl.style.display="block"},m=()=>{i.loaderEl.style.display="none"},h=()=>{i.btnEl.style.display="block"},f=()=>{i.btnEl.style.display="none"},i={formEl:document.querySelector(".form"),inputEl:document.querySelector("input[name='search-text']"),listEl:document.querySelector(".gallery"),loaderEl:document.querySelector(".loader"),btnEl:document.querySelector(".js-btn")};let a,d,o;i.formEl.addEventListener("submit",async t=>{if(t.preventDefault(),f(),R(),d=i.inputEl.value.trim(),a=1,d===""){c("Enter your query!");return}y();try{if(o=await p(d,a),m(),o.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!"),i.formEl.reset();return}g(o.hits),a+1>Math.ceil(o.totalHits/15)||h()}catch(s){m(),c(`ERROR: ${s}`),i.formEl.reset()}});i.btnEl.addEventListener("click",async()=>{a++,f(),y();try{o=await p(d,a),m(),g(o.hits);let s=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy(0,(s.height+24)*2)}catch(t){m(),c(`ERROR: ${t}`)}if(a+1>Math.ceil(o.totalHits/15)){m(),c("We're sorry, but you've reached the end of search results.");return}h()});
//# sourceMappingURL=index.js.map
