import{a as b,S as w,i as L}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const d=async(s,t)=>{try{return(await b.get("https://pixabay.com/api/",{params:{key:"53333096-0ed2bac8b305690550bcf3f17",image_type:"photo",orientation:"horizontal",safesearch:!0,q:`${s}`,per_page:15,page:t}})).data}catch(i){throw i}},$=s=>{const{webformatURL:t,largeImageURL:i,tags:c,likes:e,views:r,comments:a,downloads:E}=s;return`<li class="gallery-item">
          <a class="img-link" href="${i}"><img class="img" src="${t}" alt="${c.split(",").slice(0,3).join(",")}"/></a>
          <ul class="img-stats-list">
            <li class="img-stats-item"><h3 class="img-stats-title">likes</h3><p class="img-stats">${e}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">views</h3><p class="img-stats">${r}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">comments</h3><p class="img-stats">${a}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">downloads</h3><p class="img-stats">${E}</p></li>
          </ul>
        </li>`},q=new w(".img-link",{captionsData:"alt",captionDelay:250}),o=s=>L.show({message:`${s}`,color:"red",position:"topRight",close:!1}),p=s=>{const t=s.map(i=>$(i)).join("");l.listEl.insertAdjacentHTML("beforeend",t),q.refresh()},R=()=>{l.listEl.innerHTML=""},y=()=>{l.loaderEl.style.display="block"},g=()=>{l.loaderEl.style.display="none"},f=()=>{l.btnEl.style.display="block"},h=()=>{l.btnEl.style.display="none"},l={formEl:document.querySelector(".form"),inputEl:document.querySelector("input[name='search-text']"),listEl:document.querySelector(".gallery"),loaderEl:document.querySelector(".loader"),btnEl:document.querySelector(".js-btn")};let n=1,m,u;l.formEl.addEventListener("submit",async s=>{if(s.preventDefault(),h(),R(),m=l.inputEl.value.trim(),n=1,m===""){o("Enter your query!");return}y();try{const t=await d(m,n);if(t.hits.length===0){o("Sorry, there are no images matching your search query. Please try again!");return}u=t.totalHits,p(t.hits),u>15&&f()}catch(t){o(`ERROR: ${t}`)}finally{g(),l.formEl.reset()}});l.btnEl.addEventListener("click",async()=>{n++,h(),y();try{const s=await d(m,n);p(s.hits);let i=document.querySelector(".gallery-item").getBoundingClientRect();if(window.scrollBy(0,(i.height+24)*2),n*15>=u){o("We're sorry, but you've reached the end of search results.");return}f()}catch(s){o(`ERROR: ${s}`)}finally{g()}});
//# sourceMappingURL=index.js.map
